version: "3.8"

services:
  redis:
    image: redis:buster
    hostname: redis
    command:
      - redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - default
    restart: always

  publisher:
    build:
      context: .
      dockerfile: ./pub/Dockerfile
    volumes:
      - ./pub:/delivery_pub_sub/
    networks:
      - default
    depends_on:
      - redis
    environment:
      - WAIT_HOSTS=redis:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: always

  consumer:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./.:/delivery_app/
    networks:
      - default
    depends_on:
      - redis
    environment:
      - WAIT_HOSTS=redis:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: always
